version: '3.4'

networks:
  network-vtalk:

services:
  channelapidb:
    container_name: vtalkchanneldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abc#191199
    networks:
      - network-vtalk
    ports:
      - 8001:1433
  channel.api:
    image: ${DOCKER_REGISTRY-}channelapi
    build:
      context: .
      dockerfile: Channel.API/Dockerfile
    networks:
      - network-vtalk
    environment:
      - DB_HOST=channelapidb
      - DB_NAME=vtalk-channel
      - DB_USERID=sa
      - DB_PASSWORD=abc#191199
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.API/Dockerfile
    networks:
      - network-vtalk
    environment:
      - DB_HOST=channelapidb
      - DB_NAME=vtalk-user
      - DB_USERID=sa
      - DB_PASSWORD=abc#191199
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - network-vtalk
    ports:
      - 8080:80